import {test,expect} from '@playwright/test'

test('review, progress and training distinguish tactical evidence from positional clues',async({page,request})=>{
  const game=await(await request.post('/api/import',{data:{pgn:'1. e4 e5 2. Qh5 Nc6 3. Qxe5+ Nxe5 *',color:'w'}})).json()
  const job=await(await request.post(`/api/games/${game.id}/analysis`,{data:{}})).json()
  await expect.poll(async()=>(await(await request.get('/api/jobs/'+job.jobId)).json()).status,{timeout:30000}).toBe('complete')
  await page.goto('/')
  await page.getByRole('button',{name:'Partite',exact:true}).click()
  await page.locator('.game-list button').filter({hasText:game.title}).first().click()
  await page.getByRole('button',{name:'Posizione iniziale',exact:true}).click()
  await page.getByRole('tab',{name:'Mosse',exact:true}).click()
  const review=page.getByRole('region',{name:'Revisione passo passo'})
  await review.getByText('Tattica, posizione e strategia: cosa cambia?',{exact:true}).click()
  await expect(review).toContainText('non significa aver perso due pedoni')
  await review.getByLabel('Mossa da confrontare').selectOption('4')
  await review.getByText('Perché può cambiare la valutazione',{exact:true}).click()
  await expect(review).toContainText('Saldo materiale convenzionale')
  await expect(review).toContainText('Posizione · differenze osservabili')
  await expect(review).toContainText('Strategia · domande')
  await page.screenshot({path:'test-results/strategy-tactics-review.png',fullPage:true})
  await page.getByRole('button',{name:'Progressi',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Tattica e posizione nelle tue decisioni'})).toBeVisible()
  await expect(page.getByText('Causa da approfondire',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:/^Puzzle/}).click()
  await expect(page.getByText('Tattica, posizione e strategia: cosa cambia?',{exact:true})).toBeVisible()
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})

test('DeepSeek explanations show tactics, position, plan and uncertainty separately',async({page})=>{
  await page.route('**/api/prevention',route=>route.fulfill({json:{positions:[{id:'explain',fen:'r6k/8/5KQ1/8/8/8/8/8 w - - 0 1',turn:'w',legalMoves:['g6g7'],title:'Posizione',moveNumber:1}],stats:{firstAttempts:1,firstSuccesses:0},rule:{description:'Test'}}}))
  await page.route('**/api/prevention/explain/sessions',route=>route.fulfill({json:{id:'s',version:1,exposure:'new'}}))
  await page.route('**/api/training/prevention/explain/mistakes',route=>route.fulfill({json:[{id:1,san:'Qg8+',createdAt:'2026-09-30T10:00:00Z',lossCp:400,reference:{cp:80,mate:null},actual:{cp:-320,mate:null,san:['Qg8+','Kxg8']}}]}))
  await page.route('**/api/training/prevention/explain/mistakes/1/explain',route=>route.fulfill({json:{explanation:{reason:'La scelta perde la donna.',continuation:'Segue la cattura del re.',lesson:'Controlla le risposte.',tactical:'Il re può catturare la donna.',positional:'Il re rimane esposto: osservazione da verificare.',strategicPlan:'Metti al sicuro la donna prima di attaccare.',uncertainty:'La linea non esaurisce tutte le possibilità.'}}}))
  await page.goto('/');await page.getByRole('button',{name:'Blunder prevention',exact:true}).click();await page.getByRole('button',{name:'Inizia Blunder prevention'}).click()
  await page.getByRole('button',{name:'Spiega motivo',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Tattica · conseguenze concrete'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'Posizione · che cosa cambia'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'Strategia · piano da verificare'})).toBeVisible()
  await expect(page.getByText('La linea non esaurisce tutte le possibilità.',{exact:false})).toBeVisible()
  await page.screenshot({path:'test-results/strategy-tactics-explanation.png',fullPage:true})
})
