import {test,expect} from '@playwright/test'

test('Decision quality, optional similarity and judgment before feedback persist without rating inflation',async({page,request})=>{
  const game=await(await request.post('/api/import',{data:{pgn:'1. e4 e5 2. Qh5 Nc6 3. Qxe5+ Nxe5 *'}})).json()
  const job=await(await request.post(`/api/games/${game.id}/analysis`)).json()
  await expect.poll(async()=> (await(await request.get('/api/jobs/'+job.jobId)).json()).status).toBe('complete')
  let ratings=0;page.on('request',r=>{if(r.url().includes('/rating-positions'))ratings++})
  await page.addInitScript(id=>localStorage.setItem('chess-coach-game',id),game.id)
  await page.goto('/')
  const quality=page.getByRole('region',{name:'Qualità delle decisioni'})
  await expect(quality).toBeVisible()
  await expect(quality).toContainText('errori rilevanti')
  await expect(quality).toContainText('decisioni che conservano il vantaggio')
  expect(ratings).toBe(0)
  await expect(page.getByRole('region',{name:'Somiglianza con Maia'})).not.toBeVisible()
  await page.getByRole('button',{name:'Progressi',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Qualità delle decisioni nel tempo'})).toBeVisible()
  await page.getByRole('button',{name:'Valuta una posizione',exact:true}).click()
  const practice=page.getByRole('region',{name:'Valuta la posizione',exact:true})
  await expect(practice.getByLabel('La tua valutazione',{exact:true})).toBeVisible()
  await expect(practice.getByText('Variante di riferimento:',{exact:false})).toHaveCount(0)
  await expect(practice.getByRole('button',{name:'Analizza con Lichess',exact:false})).toHaveCount(0)
  await practice.getByLabel('La tua valutazione',{exact:true}).selectOption('much_worse')
  await practice.getByLabel('Quanto sei sicuro?').selectOption('confident')
  await practice.getByLabel('Quale minaccia temi? Quale risorsa hai?').fill('Temo un attacco ma devo verificare le difese.')
  await practice.getByLabel('Mi sembra già persa, senza possibilità di difesa.').check()
  const reply=page.waitForResponse(r=>r.url().includes('/position-judgments/')&&!r.url().endsWith('/next')&&r.request().method()==='POST')
  await practice.getByRole('button',{name:'Salva e confronta con Stockfish'}).click()
  const judgment=await(await reply).json()
  await expect(practice).toContainText('Hai indicato: Forte svantaggio')
  await expect(practice).toContainText('Variante di riferimento:')
  await expect(practice.getByRole('button',{name:'Rivedi la partita di origine'})).toBeVisible()
  await page.screenshot({path:'test-results/learning-desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/learning-mobile.png',fullPage:true})
  await practice.getByRole('button',{name:'Rivedi la partita di origine'}).click()
  await expect(page.getByRole('tab',{name:'Mosse',exact:true})).toHaveAttribute('aria-selected','true')
  expect(await page.evaluate(()=>localStorage.getItem('chess-coach-game'))).toBe(judgment.gameId)
  await page.getByRole('button',{name:'Progressi',exact:true}).click()
  await expect(page.getByText(/valutazioni registrate in totale/)).not.toContainText('0 valutazioni')
  await page.reload();await page.getByRole('button',{name:'Progressi',exact:true}).click()
  await expect(page.getByText(/valutazioni registrate in totale/)).not.toContainText('0 valutazioni')
  expect(ratings).toBe(0)
})
