import {test,expect} from '@playwright/test'
import {readFile} from 'node:fs/promises'

test('PGN exports imported clocks, headers and optional timing without changing the game',async({page,request})=>{
  const pgn='[White "Player"]\n[Black "Maia 600"]\n[Result "0-1"]\n[TimeControl "900+10"]\n\n1. e4 {[%clk 0:15:07] [%emt 0:00:03]} c6 0-1'
  const game=await(await request.post('/api/import',{data:{pgn}})).json()
  await page.addInitScript(id=>localStorage.setItem('chess-coach-game',id),game.id)
  await page.goto('/')
  await expect(page.getByRole('link',{name:'Esporta PGN'})).toBeVisible()
  const saved=page.waitForEvent('download')
  await page.getByRole('link',{name:'Esporta PGN'}).click()
  const download=await saved
  expect(download.suggestedFilename()).toBe(`sparringmate-${game.id}.pgn`)
  const text=await readFile((await download.path())!,'utf8')
  expect(text).toContain('[White "Player"]')
  expect(text).toContain('[Result "0-1"]')
  expect(text).toContain('[%clk 0:15:07]')
  expect(text).toContain('[%emt 0:00:03]')
  await page.getByRole('checkbox',{name:'Includi tempi'}).uncheck()
  const plainDownload=page.waitForEvent('download')
  await page.getByRole('link',{name:'Esporta PGN'}).click()
  const plain=await readFile((await(await plainDownload).path())!,'utf8')
  expect(plain).not.toContain('[%clk');expect(plain).not.toContain('[%emt')
  expect((await(await request.get('/api/games/'+game.id)).json()).moves).toEqual(game.moves)
})

test('new play records human and Maia elapsed time, survives reload and undo',async({page,request})=>{
  await page.goto('/')
  await page.getByRole('button',{name:'Inizia partita'}).click()
  await expect(page.getByText('Tocca a te · trascina un pezzo o usa due clic')).toBeVisible()
  await expect(page.getByRole('link',{name:'Esporta PGN'})).toBeVisible()
  const human=page.waitForResponse(r=>r.url().endsWith('/moves')&&r.request().postDataJSON()?.actor==='human')
  await page.locator('[data-square="e2"]').click();await page.locator('[data-square="e4"]').click()
  const first=await(await human).json()
  expect(first.pgn).toContain('[%emt')
  await expect.poll(async()=> (await(await request.get('/api/games/'+first.id)).json()).version,{timeout:60000}).toBe(2)
  const reply=await(await request.get('/api/games/'+first.id)).json()
  expect(reply.timedMoves).toBe(2)
  await page.reload()
  await page.getByRole('button',{name:'Continua partita',exact:true}).click()
  await expect(page.getByText('Tempi disponibili per 2 di 2 semimosse.',{exact:false})).toBeVisible()
  await page.getByRole('button',{name:'Annulla ultima mossa',exact:true}).click()
  await expect.poll(async()=> (await(await request.get('/api/games/'+first.id)).json()).version).toBe(0)
  const next=page.waitForResponse(r=>r.url().endsWith('/moves')&&r.request().postDataJSON()?.actor==='human')
  await page.locator('[data-square="d2"]').click();await page.locator('[data-square="d4"]').click()
  const branched=await(await next).json()
  expect(branched.timedMoves).toBe(1)
  expect(branched.moves).toEqual(['d2d4'])
  expect(branched.pgn).toMatch(/1\. d4 \{ \[%emt/)
})
