import {test,expect,type APIRequestContext} from '@playwright/test'

async function seed(request:APIRequestContext,black=false){
  const fen=black?'8/8/8/8/8/5kq1/8/R6K b - - 0 1':'r6k/8/5KQ1/8/8/8/8/8 w - - 0 1'
  let game=await(await request.post('/api/games',{data:{fen,color:black?'b':'w'}})).json()
  game=await(await request.post(`/api/games/${game.id}/moves`,{data:{move:black?'g3g1':'g6g8',version:0,revision:0,actor:'human'}})).json()
  const job=await(await request.post(`/api/games/${game.id}/analysis`,{data:{}})).json()
  await expect.poll(async()=> (await(await request.get('/api/jobs/'+job.jobId)).json()).status).toBe('complete')
  return game
}

test('Blunder prevention accepts alternatives, rejects the original blunder and advances to the next personal position',async({page,request})=>{
  await page.setViewportSize({width:1440,height:960})
  const white=await seed(request);const black=await seed(request,true)
  const before=(await(await request.get('/api/prevention')).json()).stats
  await page.route('**/api/prevention',async route=>{
    const response=await route.fetch();const catalog=await response.json()
    await route.fulfill({json:{...catalog,positions:catalog.positions.filter((p:{gameId:string})=>[white.id,black.id].includes(p.gameId))}})
  })
  await page.goto('/')
  await page.getByRole('button',{name:'Blunder prevention',exact:false}).click()
  await expect(page.getByRole('heading',{name:'Blunder prevention',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Inizia Blunder prevention'}).click()
  await expect(page.getByRole('heading',{name:'Evita il blunder',exact:true})).toBeVisible()
  await expect(page.getByText('Muove il Bianco',{exact:true})).toBeVisible()
  await expect(page.getByText('Avevi giocato',{exact:false})).toHaveCount(0)
  await page.locator('[data-square="g6"]').click();await page.locator('[data-square="g8"]').click()
  await expect(page.locator('[data-square="g8"] img')).toBeVisible()
  await expect(page.getByText('Osserva la mossa:',{exact:false})).toBeVisible()
  await expect(page.locator('[data-square="g6"] img')).toHaveCount(0)
  await expect(page.getByRole('heading',{name:'↻ Riprova una mossa diversa'})).toBeVisible()
  await expect(page.getByRole('region',{name:'Tentativi sbagliati'})).toContainText('Qg8+')
  await page.getByRole('button',{name:'Spiega motivo',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('DeepSeek non è configurato')
  await expect(page.locator('[data-square="g6"] img')).toBeVisible()
  await page.locator('[data-square="g6"]').click();await page.locator('[data-square="f5"]').click()
  await expect(page.getByRole('heading',{name:'✓ Blunder evitato!'})).toBeVisible()
  await expect(page.locator('[data-square="f5"] img')).toBeVisible()
  await expect(page.getByRole('heading',{name:'Avevi giocato Qg8+'})).toBeVisible()
  await page.getByRole('button',{name:'Mostra il vecchio errore'}).click()
  await expect(page.locator('[data-square="g8"] img')).toBeVisible()
  await page.getByRole('button',{name:'Mostra la mossa sicura'}).click()
  await expect(page.locator('[data-square="f5"] img')).toBeVisible()
  await page.screenshot({path:'test-results/blunder-prevention-desktop.png',fullPage:true})
  await page.getByRole('button',{name:'Prossima posizione'}).click()
  await expect(page.getByRole('heading',{name:'Evita il blunder',exact:true})).toBeVisible()
  await expect(page.getByText('Muove il Nero',{exact:true})).toBeVisible()
  await expect(page.locator('.square').first()).toHaveAttribute('data-square','h1')
  await page.locator('[data-square="g3"]').click();await page.locator('[data-square="f4"]').click()
  await expect(page.getByRole('heading',{name:'✓ Blunder evitato!'})).toBeVisible()
  const catalog=await(await request.get('/api/prevention')).json()
  expect(catalog.stats).toEqual({firstAttempts:before.firstAttempts+2,firstSuccesses:before.firstSuccesses+1})
  expect((await(await request.get('/api/games/'+white.id)).json()).moves).toEqual(white.moves)
  expect((await(await request.get('/api/games/'+black.id)).json()).moves).toEqual(black.moves)
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/blunder-prevention-mobile.png',fullPage:true})
  await page.getByRole('button',{name:'Rivedi nella partita'}).click()
  await expect(page.getByRole('heading',{name:'Capisci le tue scelte.'})).toBeVisible()
  await expect(page.locator('[data-square="g3"] img')).toBeVisible()
})

test('empty catalog explains how personal positions are obtained',async({page})=>{
  await page.route('**/api/prevention',route=>route.fulfill({json:{positions:[],stats:{firstAttempts:0,firstSuccesses:0},analyzedGames:0,rule:{description:'Soglia −1,00 dal tuo punto di vista.'}}}))
  await page.goto('/')
  await page.getByRole('button',{name:'Blunder prevention',exact:false}).click()
  await expect(page.getByText('Nessun blunder evitabile disponibile.',{exact:false})).toBeVisible()
  await page.getByRole('button',{name:'Apri le tue partite'}).click()
  await expect(page.getByRole('heading',{name:'Le tue partite.',exact:true})).toBeVisible()
})
