import {test,expect} from '@playwright/test'

test('Puzzle feedback distinguishes retry, success and reveal and advances without repeating completed puzzles',async({page,request})=>{
  const ids:string[]=[]
  for(let i=0;i<2;i++){
    const game=await(await request.post('/api/games',{data:{fen:'7k/8/5KQ1/8/8/8/8/8 w - - 0 1'}})).json()
    await request.post(`/api/games/${game.id}/moves`,{data:{move:'g6g8',version:0,revision:0,actor:'human'}})
    const job=await(await request.post(`/api/games/${game.id}/analysis`,{data:{}})).json()
    await expect.poll(async()=>(await(await request.get('/api/jobs/'+job.jobId)).json()).status,{timeout:30000}).toBe('complete')
    ids.push(game.id)
  }
  await page.route('**/api/exercises',async route=>{
    const response=await route.fetch()
    const exercises=await response.json()
    await route.fulfill({json:exercises.filter((ex:{gameId:string})=>ids.includes(ex.gameId))})
  })
  const sessions:string[]=[]
  page.on('request',req=>{if(req.method()==='POST'&&/\/exercises\/[^/]+\/sessions$/.test(req.url()))sessions.push(req.url())})
  await page.goto('/')
  await page.getByRole('button',{name:/^Puzzle/}).click()
  const feedback=page.getByRole('region',{name:'Esito del puzzle'})
  await expect(feedback).toContainText('Trova una buona mossa')
  await page.locator('[data-square="g6"]').click()
  await page.locator('[data-square="g8"]').click()
  await expect(page.locator('[data-square="g8"] img')).toBeVisible()
  await expect(feedback).toContainText('Osserva la mossa:')
  await expect(feedback).toContainText('La scacchiera è tornata alla posizione iniziale',{timeout:30000})
  await expect(page.getByRole('region',{name:'Tentativi sbagliati'})).toContainText('Qg8+')
  await expect(feedback.getByRole('button',{name:'Prossimo puzzle'})).toHaveCount(0)
  await expect(page.locator('[data-square="g6"] img')).toBeVisible()
  await page.setViewportSize({width:390,height:844})
  await page.locator('[data-square="g6"]').click()
  await page.locator('[data-square="g7"]').click()
  await expect(feedback).toContainText('Mossa corretta!',{timeout:30000})
  await expect(page.locator('[data-square="g7"] img')).toBeVisible()
  await expect(page.locator('[data-square="g6"] img')).toHaveCount(0)
  const next=feedback.getByRole('button',{name:'Prossimo puzzle'})
  await expect(next).toBeEnabled()
  await expect(next).toBeInViewport()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/puzzle-correct-mobile.png',fullPage:true})
  await next.click()
  await expect(feedback).toContainText('Trova una buona mossa')
  expect(sessions).toHaveLength(2)
  expect(sessions[0]).not.toBe(sessions[1])
  await expect(page.locator('[data-square="g6"] img')).toBeVisible()
  await page.getByRole('button',{name:'Mostra soluzione',exact:true}).click()
  await expect(feedback).toContainText('Soluzione mostrata')
  await expect(feedback).not.toContainText('Mossa corretta!')
  await expect(feedback).toContainText('Non ci sono altri puzzle')
  await expect(next).toHaveCount(0)
  await feedback.getByRole('button',{name:'Ricomincia gli esercizi'}).click()
  await expect(feedback).toContainText('Trova una buona mossa')
  await expect(feedback).not.toContainText('Non ci sono altri puzzle')
  expect(sessions).toHaveLength(3)
})
