import {test,expect,type Page} from '@playwright/test'

async function play(page:Page,move:string){
  const response=page.waitForResponse(r=>r.url().endsWith('/moves')&&r.request().postDataJSON()?.actor==='human')
  await page.locator(`[data-square="${move.slice(0,2)}"]`).click()
  await page.locator(`[data-square="${move.slice(2,4)}"]`).click()
  await response
}

test('Undo while Maia thinks cancels its old reply; a new move can be played and both plies undone',async({page,request})=>{
  await page.addInitScript(()=>{Math.random=()=>0.5})
  await page.goto('/')
  await page.getByRole('button',{name:'Inizia partita'}).click()
  const undo=page.getByRole('button',{name:'Annulla ultima mossa',exact:true})
  await expect(undo).toBeDisabled()
  await play(page,'e2e4')
  await expect(page.getByText('Maia sta pensando…',{exact:true})).toBeVisible()
  await undo.click()
  await expect(page.getByText('Ultima mossa annullata. Tocca a te.')).toBeVisible()
  const id=await page.evaluate(()=>localStorage.getItem('chess-coach-game'))
  await page.waitForTimeout(3500)
  let game=await(await request.get('/api/games/'+id)).json()
  expect(game.moves).toEqual([]);expect(game.revision).toBe(1)
  await expect(undo).toBeDisabled()
  await play(page,'d2d4')
  await expect(page.getByText('Tocca a te · trascina un pezzo o usa due clic')).toBeVisible({timeout:60000})
  game=await(await request.get('/api/games/'+id)).json()
  expect(game.version).toBe(2);expect(game.moves[0]).toBe('d2d4')
  await undo.click()
  await expect(undo).toBeDisabled()
  expect((await(await request.get('/api/games/'+id)).json()).moves).toEqual([])
  await expect(page.getByRole('alert')).toHaveCount(0)
})

test('Drill undo preserves its seed and resets the decision counter',async({page,request})=>{
  await page.addInitScript(()=>{Math.random=()=>0.5})
  await page.goto('/')
  await page.getByRole('button',{name:'Drill',exact:true}).click()
  await page.getByRole('button',{name:'Avvia Partita italiana'}).click()
  const undo=page.getByRole('button',{name:'Annulla ultima mossa',exact:true})
  await expect(undo).toBeDisabled()
  const id=await page.evaluate(()=>localStorage.getItem('chess-coach-drill'))
  const seed=await(await request.get('/api/games/'+id)).json()
  await play(page,seed.legalMoves[0])
  await expect(page.getByText('1 / 5 decisioni')).toBeVisible()
  await undo.click()
  await expect(page.getByText('0 / 5 decisioni')).toBeVisible()
  await page.waitForTimeout(3500)
  expect((await(await request.get('/api/games/'+id)).json()).moves).toEqual(seed.moves)
  await expect(undo).toBeDisabled()
})

test('Real Maia Elo comparison is persisted, reloadable and handles too few decisions',async({page,request})=>{
  const pgn='1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O Be7 6. Re1 b5 7. Bb3 d6 8. c3 O-O 9. h3 Nb8 10. d4 Nbd7 11. Nbd2 Bb7 12. Bc2 Re8 *'
  const game=await(await request.post('/api/import',{data:{pgn}})).json()
  await page.addInitScript(id=>localStorage.setItem('chess-coach-game',id),game.id)
  await page.goto('/')
  const panel=page.getByRole('region',{name:'Valutazione Elo della partita'})
  await panel.getByRole('button',{name:'Stima Elo della partita'}).click()
  await expect(panel.getByRole('button',{name:'Ricalcola stima Elo'})).toBeVisible({timeout:90000})
  const saved=(await(await request.get('/api/games/'+game.id)).json()).rating
  expect(saved.positions).toBe(12)
  expect(saved.method).toBe('maia3-likelihood-v1')
  expect(saved.logScores).toHaveLength(11)
  expect(saved.logScores.every((v:number)=>Number.isFinite(v)&&v<=0)).toBe(true)
  await expect(panel).toContainText('Fascia compatibile')
  await expect(panel).toContainText('avversario di 1500 Elo')
  await page.screenshot({path:'test-results/elo-desktop.png',fullPage:true})
  await page.getByRole('button',{name:'Progressi',exact:true}).click()
  await page.getByRole('button',{name:'Rivedi',exact:true}).click()
  await expect(panel).toContainText('Fascia compatibile')
  await page.reload()
  await expect(panel).toContainText('Fascia compatibile')
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/elo-mobile.png',fullPage:true})
  await page.getByRole('button',{name:'Importa PGN',exact:false}).click()
  await page.getByLabel('Partita PGN').fill('1. d4 d5 *')
  await page.getByRole('button',{name:'Importa partita',exact:true}).click()
  await panel.getByRole('button',{name:'Stima Elo della partita'}).click()
  await expect(panel.getByRole('alert')).toContainText('Servono almeno 10')
})
