import {test,expect,type Page} from '@playwright/test'

async function play(page:Page,move:string){
  const response=page.waitForResponse(r=>r.url().endsWith('/moves')&&r.request().postDataJSON()?.actor==='human')
  await page.locator(`[data-square="${move.slice(0,2)}"]`).click()
  await page.locator(`[data-square="${move.slice(2,4)}"]`).click()
  await response
}

test('Checkmate starts Elo automatically in play, retains the calculation in review and restores the saved score',async({page,request})=>{
  const pgn='1. e4 e5 2. Nf3 d6 3. d4 Bg4 4. dxe5 Bxf3 5. Qxf3 dxe5 6. Bc4 Nf6 7. Qb3 Qe7 8. Nc3 c6 9. Bg5 b5 10. Nxb5 cxb5 11. Bxb5+ Nbd7 12. O-O-O Rd8 13. Rxd7 Rxd7 14. Rd1 Qe6 15. Bxd7+ Nxd7 16. Qb8+ Nxb8 17. Rd8#'
  const imported=await(await request.post('/api/import',{data:{pgn}})).json()
  let game=await(await request.post('/api/games',{data:{}})).json()
  for(const move of imported.moves.slice(0,-1)){
    game=await(await request.post(`/api/games/${game.id}/moves`,{data:{move,version:game.version,revision:game.revision,actor:game.turn===game.playerColor?'human':'maia'}})).json()
  }
  let starts=0,saves=0
  page.on('request',req=>{if(req.url().endsWith('/rating-positions'))starts++;if(req.url().endsWith('/rating')&&req.method()==='POST')saves++})
  await page.addInitScript(id=>localStorage.setItem('chess-coach-game',id),game.id)
  await page.goto('/')
  await expect(page.getByRole('button',{name:'Stima Elo della partita'})).toBeVisible()
  await page.getByRole('button',{name:'Gioca',exact:true}).click()
  await play(page,imported.moves.at(-1))
  const panel=page.getByRole('region',{name:'Valutazione Elo della partita'})
  await expect(panel).toContainText('Hai vinto · 1-0')
  await expect(panel.getByText(/Confronto delle tue mosse/)).toBeVisible()
  await page.getByRole('button',{name:'Rivedi',exact:true}).click()
  await expect(panel).toContainText('profilo Maia',{timeout:90000})
  expect(starts).toBe(1);expect(saves).toBe(1)
  await page.reload()
  await expect(panel).toContainText('profilo Maia')
  await page.getByRole('button',{name:'Gioca',exact:true}).click()
  await expect(panel).toContainText('profilo Maia')
  expect(starts).toBe(1);expect(saves).toBe(1)
})

test('Reopening a finished short game explains why no Elo is available without retrying endlessly',async({page,request})=>{
  const game=await(await request.post('/api/import',{data:{pgn:'1. f3 e5 2. g4 Qh4#',color:'w'}})).json()
  let requests=0
  page.on('request',req=>{if(req.url().endsWith('/rating-positions'))requests++})
  await page.addInitScript(id=>localStorage.setItem('chess-coach-game',id),game.id)
  await page.goto('/')
  const panel=page.getByRole('region',{name:'Valutazione Elo della partita'})
  await expect(panel).toContainText('Hai perso · 0-1')
  await expect(panel.getByRole('alert')).toContainText('Partita troppo breve')
  await expect(panel).toContainText('2 tue decisioni non obbligate')
  expect(requests).toBe(1)
  await expect(panel).not.toContainText('Continua la partita')
})

test('Undo while Maia thinks cancels its old reply; a new move can be played and both plies undone',async({page,request})=>{
  await page.addInitScript(()=>{Math.random=()=>0.5})
  await page.goto('/')
  await page.getByRole('button',{name:'Inizia partita'}).click()
  const undo=page.getByRole('button',{name:'Annulla ultima mossa',exact:true})
  await expect(undo).toBeDisabled()
  await play(page,'e2e4')
  await expect(page.getByText('Maia sta pensando…',{exact:true})).toBeVisible()
  await undo.click()
  await expect(page.getByText('Ultima mossa annullata. Tocca a te.')).toBeVisible()
  const id=await page.evaluate(()=>localStorage.getItem('chess-coach-game'))
  await page.waitForTimeout(3500)
  let game=await(await request.get('/api/games/'+id)).json()
  expect(game.moves).toEqual([]);expect(game.revision).toBe(1)
  await expect(undo).toBeDisabled()
  await play(page,'d2d4')
  await expect(page.getByText('Tocca a te · trascina un pezzo o usa due clic')).toBeVisible({timeout:60000})
  game=await(await request.get('/api/games/'+id)).json()
  expect(game.version).toBe(2);expect(game.moves[0]).toBe('d2d4')
  await undo.click()
  await expect(undo).toBeDisabled()
  expect((await(await request.get('/api/games/'+id)).json()).moves).toEqual([])
  await expect(page.getByRole('alert')).toHaveCount(0)
})

test('Drill undo preserves its seed and resets the decision counter',async({page,request})=>{
  await page.addInitScript(()=>{Math.random=()=>0.5})
  await page.goto('/')
  await page.getByRole('button',{name:'Drill',exact:true}).click()
  await page.getByRole('button',{name:'Avvia Partita italiana'}).click()
  const undo=page.getByRole('button',{name:'Annulla ultima mossa',exact:true})
  await expect(undo).toBeDisabled()
  const id=await page.evaluate(()=>localStorage.getItem('chess-coach-drill'))
  const seed=await(await request.get('/api/games/'+id)).json()
  await play(page,seed.legalMoves[0])
  await expect(page.getByText('1 / 5 decisioni')).toBeVisible()
  await undo.click()
  await expect(page.getByText('0 / 5 decisioni')).toBeVisible()
  await page.waitForTimeout(3500)
  expect((await(await request.get('/api/games/'+id)).json()).moves).toEqual(seed.moves)
  await expect(undo).toBeDisabled()
})

test('Real Maia Elo comparison is persisted, reloadable and handles too few decisions',async({page,request})=>{
  const pgn='1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O Be7 6. Re1 b5 7. Bb3 d6 8. c3 O-O 9. h3 Nb8 10. d4 Nbd7 11. Nbd2 Bb7 12. Bc2 Re8 *'
  const game=await(await request.post('/api/import',{data:{pgn}})).json()
  await page.addInitScript(id=>localStorage.setItem('chess-coach-game',id),game.id)
  await page.goto('/')
  const panel=page.getByRole('region',{name:'Valutazione Elo della partita'})
  await panel.getByRole('button',{name:'Stima Elo della partita'}).click()
  await expect(panel.getByRole('button',{name:'Ricalcola stima Elo'})).toBeVisible({timeout:90000})
  const saved=(await(await request.get('/api/games/'+game.id)).json()).rating
  expect(saved.positions).toBe(12)
  expect(saved.method).toBe('maia3-drill-match-v2')
  expect(saved.logScores).toHaveLength(21)
  expect(saved.logScores.every((v:number)=>Number.isFinite(v)&&v<=0)).toBe(true)
  await expect(panel).toContainText('profilo Maia')
  await expect(panel).toContainText('Scala di riferimento Maia/Lichess')
  await page.screenshot({path:'test-results/elo-desktop.png',fullPage:true})
  await page.getByRole('button',{name:'Progressi',exact:true}).click()
  await page.getByRole('button',{name:'Rivedi',exact:true}).click()
  await expect(panel).toContainText('profilo Maia')
  await page.reload()
  await expect(panel).toContainText('profilo Maia')
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/elo-mobile.png',fullPage:true})
  await page.getByRole('button',{name:'Importa PGN',exact:false}).click()
  await page.getByLabel('Partita PGN').fill('1. d4 d5 *')
  await page.getByRole('button',{name:'Importa partita',exact:true}).click()
  await panel.getByRole('button',{name:'Stima Elo della partita'}).click()
  await expect(panel.getByRole('alert')).toContainText('Servono almeno 10')
})
